### ISSUE TITLE
Encoding planet.osm.pbf

### ISSUE THREAD

**Issue by wipfli** [wipfli/positioned-glyph-font#2]
The planet.osm.pbf has roughly 114 million name* tags. Let's encode all of them and create a planet-encoded.osm.pbf file. 

Steps

Download planet.osm.pbf

```
osmium tags-filter planet.osm.pbf '/name*' -f osm -R | grep 'k="name' > names.txt
```

```
sed 's/    <tag k="name.*" v="//' names.txt | sed 's/"\/>//' > labels.txt
```

**Comment by wipfli** [comment]
There are 36 million unique name* tag values.


```python
import json

labels = set([])
i = 0
with open('labels.txt') as f:
    for line in f:
        labels.add(line.strip())
        i += 1
        if i % 1000000 == 0:
            print(i, len(labels))

print(i, len(labels))

with open('labels.json', 'w') as f:
    json.dump(list(labels), f, indent=2)
```

**Comment by wipfli** [comment]
Requires 10564 unique harfbuzz glyphs, and when downscaled by 1/64 only 6348 unique MapLibre SDF glyphs.

Uses 


NotoSans-Regular.ttf
NotoSansBalinese-Regular.ttf
NotoSansBengali-Regular.ttf
NotoSansBuginese-Regular.ttf
NotoSansCanadianAboriginal-Regular.ttf
NotoSansCherokee-Regular.ttf
NotoSansCoptic-Regular.ttf
NotoSansDevanagari-Regular.ttf
NotoSansEthiopic-Regular.ttf
NotoSansGeorgian-Regular.ttf
NotoSansGlagolitic-Regular.ttf
NotoSansGujarati-Regular.ttf
NotoSansGurmukhi-Regular.ttf
NotoSansJavanese-Regular.ttf
NotoSansKannada-Regular.ttf
NotoSansKhmer-Regular.ttf
NotoSansLao-Regular.ttf
NotoSansLisu-Regular.ttf
NotoSansMalayalam-Regular.ttf
NotoSansMath-Regular.ttf
NotoSansMeeteiMayek-Regular.ttf
NotoSansMongolian-Regular.ttf
NotoSansMyanmar-Regular.ttf
NotoSansNKo-Regular.ttf
NotoSansNewTaiLue-Regular.ttf
NotoSansOlChiki-Regular.ttf
NotoSansOriya-Regular.ttf
NotoSansRunic-Regular.ttf
NotoSansSinhala-Regular.ttf
NotoSansSundanese-Regular.ttf
NotoSansSylotiNagri-Regular.ttf
NotoSansSymbols-Regular.ttf
NotoSansSymbols2-Regular.ttf
NotoSansSyriac-Regular.ttf
NotoSansTagalog-Regular.ttf
NotoSansTaiLe-Regular.ttf
NotoSansTamil-Regular.ttf
NotoSansTelugu-Regular.ttf
NotoSansThaana-Regular.ttf
NotoSansThai-Regular.ttf
NotoSansTibetan-Regular.ttf
NotoSansTifinagh-Regular.ttf

and ignores these ranges:

```py
ignored_unicode_ranges = {
    'low codepoints': {'first_including': 0x0000, 'last_including': 0x06FF},
    'Arabic Supplement': {'first_including': 0x0750, 'last_including': 0x077F},
    'Arabic Extended-A': {'first_including': 0x08A0, 'last_including': 0x08FF},
    'Hangul Jamo': {'first_including': 0x1100, 'last_including': 0x11FF},
    'Box Drawing': {'first_including': 0x2500, 'last_including': 0x257F},
    'Block Elements': {'first_including': 0x2580, 'last_including': 0x259F},
    'Dingbats': {'first_including': 0x2700, 'last_including': 0x27BF},
    'CJK Radicals Supplement': {'first_including': 0x2E80, 'last_including': 0x2EFF},
    'Kangxi Radicals': {'first_including': 0x2F00, 'last_including': 0x2FDF},
    'Ideographic Description Characters': {'first_including': 0x2FF0, 'last_including': 0x2FFF},
    'CJK Symbols and Punctuation': {'first_including': 0x3000, 'last_including': 0x303F},
    'Hiragana': {'first_including': 0x3040, 'last_including': 0x309F},
    'Katakana': {'first_including': 0x30A0, 'last_including': 0x30FF},
    'Bopomofo': {'first_including': 0x3100, 'last_including': 0x312F},
    'Hangul Compatibility Jamo': {'first_including': 0x3130, 'last_including': 0x318F},
    'Kanbun': {'first_including': 0x3190, 'last_including': 0x319F},
    'Bopomofo Extended': {'first_including': 0x31A0, 'last_including': 0x31BF},
    'CJK Strokes': {'first_including': 0x31C0, 'last_including': 0x31EF},
    'Katakana Phonetic Extensions': {'first_including': 0x31F0, 'last_including': 0x31FF},
    'Enclosed CJK Letters and Months': {'first_including': 0x3200, 'last_including': 0x32FF},
    'CJK Compatibility': {'first_including': 0x3300, 'last_including': 0x33FF},
    'CJK Unified Ideographs Extension A': {'first_including': 0x3400, 'last_including': 0x4DBF},
    'Yijing Hexagram Symbols': {'first_including': 0x4DC0, 'last_including': 0x4DFF},
    'CJK Unified Ideographs': {'first_including': 0x4E00, 'last_including': 0x9FFF},
    'Yi Syllables': {'first_including': 0xA000, 'last_including': 0xA48F},
    'Yi Radicals': {'first_including': 0xA490, 'last_including': 0xA4CF},
    'Hangul Jamo Extended-A': {'first_including': 0xA960, 'last_including': 0xA97F},
    'Hangul Syllables': {'first_including': 0xAC00, 'last_including': 0xD7AF},
    'Hangul Jamo Extended-B': {'first_including': 0xD7B0, 'last_including': 0xD7FF},
    'Private Use Area': {'first_including': 0xE000, 'last_including': 0xF8FF},
    'CJK Compatibility Ideographs': {'first_including': 0xF900, 'last_including': 0xFAFF},
    'Alphabetic Presentation Forms': {'first_including': 0xFB00, 'last_including': 0xFB4F},
    'Arabic Presentation Forms-A': {'first_including': 0xFB50, 'last_including': 0xFDFF},
    'Variation Selectors': {'first_including': 0xFE00, 'last_including': 0xFE0F},
    'Vertical Forms': {'first_including': 0xFE10, 'last_including': 0xFE1F},
    'Small Form Variants': {'first_including': 0xFE50, 'last_including': 0xFE6F},
    'CJK Compatibility Forms': {'first_including': 0xFE30, 'last_including': 0xFE4F},
    'Arabic Presentation Forms-B': {'first_including': 0xFE70, 'last_including': 0xFEFF},
    'Halfwidth and Fullwidth Forms': {'first_including': 0xFF00, 'last_including': 0xFFEF},
}
```
 
ignored codepoints 52272 available codepoints 13264

**Comment by wipfli** [comment]
Some more stats:

The OSM planet has 36,159,030 unique labels, i.e., values of tags that have a key starting with `name`. Out of these, 35,342,178 do not require any encoding with the above ignore list. 

So there are actually only 816,852 labels in OSM that need to be encoded...

**Comment by wipfli** [comment]
Harfbuzz glyphs:

| Font | Unique Positioned Glyphs | Unique Glyphs Indexes | Ratio |
|----|----|----| --- |
| NotoSansEthiopic-Regular.ttf  |  1596  |  303 | 5.27 |
| NotoSansTelugu-Regular.ttf  |  1120  |  378 | 2.96 |
| NotoSansMyanmar-Regular.ttf  |  902  |  251 | 3.59 |
| NotoSansThai-Regular.ttf  |  759  |  109 | 6.96 |
| NotoSansKhmer-Regular.ttf  |  642  |  205 | 3.13 |
| NotoSansDevanagari-Regular.ttf  |  583  |  345 | 1.69 |
| NotoSansTibetan-Regular.ttf  |  408  |  274 | 1.49 |
| NotoSansKannada-Regular.ttf  |  396  |  290 | 1.37 |
| NotoSansBengali-Regular.ttf  |  356  |  273 | 1.30 |
| NotoSans-Regular.ttf  |  320  |  320 | 1.00 |
| NotoSansGujarati-Regular.ttf  |  306  |  197 | 1.55 |
| NotoSansLao-Regular.ttf  |  271  |  89 | 3.04 |
| NotoSansTamil-Regular.ttf  |  264  |  128 | 2.06 |
| NotoSansSinhala-Regular.ttf  |  222  |  168 | 1.32 |
| NotoSansOriya-Regular.ttf  |  221  |  143 | 1.55 |
| NotoSansCherokee-Regular.ttf  |  209  |  81 | 2.58 |
| NotoSansThaana-Regular.ttf  |  207  |  44 | 4.70 |
| NotoSansMalayalam-Regular.ttf  |  201  |  142 | 1.42 |
| NotoSansSyriac-Regular.ttf  |  194  |  93 | 2.09 |
| NotoSansCanadianAboriginal-Regular.ttf  |  187  |  187 | 1.00 |
| NotoSansMongolian-Regular.ttf  |  161  |  161 | 1.00 |
| NotoSansGurmukhi-Regular.ttf  |  146  |  90 | 1.62 |
| NotoSansTifinagh-Regular.ttf  |  141  |  50 | 2.82 |
| NotoSansGeorgian-Regular.ttf  |  127  |  72 | 1.76 |
| NotoSansSymbols2-Regular.ttf  |  92  |  92 | 1.00 |
| NotoSansNKo-Regular.ttf  |  81  |  56 | 1.45 |
| NotoSansSymbols-Regular.ttf  |  79  |  79 | 1.00 |
| NotoSansMeeteiMayek-Regular.ttf  |  65  |  42 | 1.55 |
| NotoSansMath-Regular.ttf  |  50  |  50 | 1.00 |
| NotoSansBuginese-Regular.ttf  |  49  |  24 | 2.04 |
| NotoSansOlChiki-Regular.ttf  |  42  |  42 | 1.00 |
| NotoSansTaiLe-Regular.ttf  |  28  |  28 | 1.00 |
| NotoSansCoptic-Regular.ttf  |  27  |  27 | 1.00 |
| NotoSansJavanese-Regular.ttf  |  23  |  22 | 1.05 |
| NotoSansLisu-Regular.ttf  |  23  |  23 | 1.00 |
| NotoSansNewTaiLue-Regular.ttf  |  16  |  16 | 1.00 |
| NotoSansBalinese-Regular.ttf  |  12  |  12 | 1.00 |
| NotoSansRunic-Regular.ttf  |  10  |  10 | 1.00 |
| NotoSansGlagolitic-Regular.ttf  |  9  |  9 | 1.00 |
| NotoSansTagalog-Regular.ttf  |  8  |  8 | 1.00 |
| NotoSansSylotiNagri-Regular.ttf  |  7  |  7 | 1.00 |
| NotoSansSundanese-Regular.ttf  |  4  |  4 | 1.00 |
| Total |  10564  |  4944 | 2.14 |

**Comment by wipfli** [comment]
MapLibre Downscaled Glyphs:

| Font | Unique Positioned Glyphs | Unique Glyph Indexes | Ratio |
| --- | --- | --- | --- |
| NotoSansTelugu-Regular.ttf  |  625  |  378 | 1.65 |
| NotoSansEthiopic-Regular.ttf  |  589  |  303 | 1.94 |
| NotoSansDevanagari-Regular.ttf  |  409  |  345 | 1.19 |
| NotoSansKannada-Regular.ttf  |  363  |  290 | 1.25 |
| NotoSans-Regular.ttf  |  320  |  320 | 1.00 |
| NotoSansTibetan-Regular.ttf  |  319  |  274 | 1.16 |
| NotoSansMyanmar-Regular.ttf  |  313  |  251 | 1.25 |
| NotoSansKhmer-Regular.ttf  |  303  |  205 | 1.48 |
| NotoSansBengali-Regular.ttf  |  296  |  273 | 1.08 |
| NotoSansGujarati-Regular.ttf  |  239  |  197 | 1.21 |
| NotoSansCanadianAboriginal-Regular.ttf  |  187  |  187 | 1.00 |
| NotoSansSinhala-Regular.ttf  |  182  |  168 | 1.08 |
| NotoSansThai-Regular.ttf  |  175  |  109 | 1.61 |
| NotoSansOriya-Regular.ttf  |  170  |  143 | 1.19 |
| NotoSansMalayalam-Regular.ttf  |  167  |  142 | 1.18 |
| NotoSansTamil-Regular.ttf  |  166  |  128 | 1.30 |
| NotoSansMongolian-Regular.ttf  |  161  |  161 | 1.00 |
| NotoSansSyriac-Regular.ttf  |  154  |  93 | 1.66 |
| NotoSansLao-Regular.ttf  |  141  |  89 | 1.58 |
| NotoSansCherokee-Regular.ttf  |  133  |  81 | 1.64 |
| NotoSansThaana-Regular.ttf  |  97  |  44 | 2.20 |
| NotoSansGurmukhi-Regular.ttf  |  96  |  90 | 1.07 |
| NotoSansSymbols2-Regular.ttf  |  92  |  92 | 1.00 |
| NotoSansGeorgian-Regular.ttf  |  81  |  72 | 1.12 |
| NotoSansSymbols-Regular.ttf  |  79  |  79 | 1.00 |
| NotoSansNKo-Regular.ttf  |  74  |  56 | 1.32 |
| NotoSansTifinagh-Regular.ttf  |  71  |  50 | 1.42 |
| NotoSansMath-Regular.ttf  |  50  |  50 | 1.00 |
| NotoSansMeeteiMayek-Regular.ttf  |  49  |  42 | 1.17 |
| NotoSansOlChiki-Regular.ttf  |  42  |  42 | 1.00 |
| NotoSansBuginese-Regular.ttf  |  39  |  24 | 1.62 |
| NotoSansTaiLe-Regular.ttf  |  28  |  28 | 1.00 |
| NotoSansCoptic-Regular.ttf  |  27  |  27 | 1.00 |
| NotoSansLisu-Regular.ttf  |  23  |  23 | 1.00 |
| NotoSansJavanese-Regular.ttf  |  22  |  22 | 1.00 |
| NotoSansNewTaiLue-Regular.ttf  |  16  |  16 | 1.00 |
| NotoSansBalinese-Regular.ttf  |  12  |  12 | 1.00 |
| NotoSansRunic-Regular.ttf  |  10  |  10 | 1.00 |
| NotoSansGlagolitic-Regular.ttf  |  9  |  9 | 1.00 |
| NotoSansTagalog-Regular.ttf  |  8  |  8 | 1.00 |
| NotoSansSylotiNagri-Regular.ttf  |  7  |  7 | 1.00 |
| NotoSansSundanese-Regular.ttf  |  4  |  4 | 1.00 |
| Total |  6348  |  4944 | 1.28 |

**Comment by 1ec5** [comment]
Don’t forget OpenHistoricalMap and all its hieroglyphs, cuneiform, and runes – and all the complex historical scripts I know nothing about!

**Comment by wipfli** [comment]
Factored out into https://github.com/wipfli/word-corpus
